### ISSUE TITLE
non-MULTIPLICITY perls: test t/020_op.t broken

### ISSUE THREAD

**Issue by tsee** [mbarbon/perl-libjit#1]
'bout time we used these shiny github issue thingies instead of email for exchanging bugs. :)

Even after my compile-fixes for non-MULTIPLICITY perls from this morning, there's still failing tests in t/020_op.t.

In a nutshell:

```
    t/020_op.t ....... Can't call method "object_2svref" without a package or object reference at t/020_op.t line 42.
```

Which when adorned with a Data::Dumper call becomes:

```
    t/020_op.t ....... $VAR1 = 34465400;
    Can't call method "object_2svref" without a package or object reference at t/020_op.t line 43.
```

Not sure how to fix that and whether the error is (as I believe) in the test itself, in that the OP tree (specifically CONST OPs) looks different in unthreaded perls, or whatever. Train arriving so can't find out.

We should probably be vigilant about testing with both threaded/unthreaded from here on out since we'll just do a bunch more OP tree munging and finding such problems much later is going to be much more of a hassle than up front.

**Comment by tsee** [comment]
On top of that, if I install despite test failure, I get a test failure in Perl-JIT. Filing here since it might be related.

```
t/021_runtime_types.t ... 1/24 Use of uninitialized value within @_ in list assignment at (eval 43) line 3.
panic: attempt to copy value  to a freed scalar 1e719f8 at (eval 43) line 3.
# Looks like you planned 24 tests but ran 12.
# Looks like your test exited with 255 just after 12.
```

**Comment by mbarbon** [comment]
Not related: the test failure is just a test glitch (fixed).

**Comment by mbarbon** [comment]
Funny it only fails like this on non-threaded perls.  Fixed.
